version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: 'postgres:11.5-alpine'
    environment:
      POSTGRES_PASSWORD: legendado
